### ISSUE TITLE
Fails to find bone (name) for Bandit Air Defense Launcher

### ISSUE THREAD

**Issue by Sellkee** [Maxxxel/SR-ImpEx-for-Blender#13]
When importing the Bandit building `air_defense_launcher` it fails to find bone names and stops importing part way.

![image](https://github.com/user-attachments/assets/9d2df236-3bae-462b-bff4-8740ee32cf04)
[air_defense_launcher.zip](https://github.com/user-attachments/files/17617299/air_defense_launcher.zip)

**Comment by Maxxxel** [comment]
Yes, I know some models bug on bones. Im working on new version of my plugin right now that will import those models without any problems.

I will push it later.

**Comment by Maxxxel** [comment]
@Sellkee Try this: https://github.com/Maxxxel/SR-ImpEx-for-Blender/blob/Restructure/SR-ImpEx-for-Blender.zip

This is my latest work in progress version. I changed a lot, but it should be possible to import any model.

**Comment by Maxxxel** [comment]
Edit: the problem lays within the model itself as the rigger gave the bones damn long names which isn't supported by Blender. By cutting the names into unique ones, the model can be imported without a problem.
